- name: copy configuration files
  ansible.builtin.copy:
    src={{ item }}
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/{{ item }}
    force=no
    mode=644
    owner=www-data
    group=www-data
  with_items:
    - Skins.php

- name: check out skins from git
  ansible.builtin.git:
    repo={{ item.url }}
    dest={{ MW_CODE_DIRECTORY }}/skins/{{ item.name }}
    version={{ item.version }}
    force=yes
    accept_hostkey=yes
  with_items: "{{ SKINS }}"

- name: configure skins
  ansible.builtin.lineinfile:
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Skins.php
    regexp="wfLoadSkin\(\s*['\"]{{ item.name }}['\"]"
    line="wfLoadSkin( '{{ item.name }}' );"
  with_items: "{{ SKINS }}"
