- name: create global wiki farm config file
  ansible.builtin.template:
    src=wikifarm.conf.j2
    dest="{{ APACHE_CONF_DIRECTORY }}/wikifarm.conf"
    mode=0644

- name: edit Apache configuration file 1/2
  ansible.builtin.replace:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="/var/www/html"
    replace="{{ APACHE_HTML_DIRECTORY }}"
    backup=yes

- name: edit Apache configuration file 2/2
  ansible.builtin.lineinfile:
    dest=/etc/apache2/apache2.conf
    insertafter=EOF
    line="Include {{ APACHE_CONF_DIRECTORY }}/wikifarm.conf"

- name: copy wiki farm index file
  ansible.builtin.template:
    src=wiki_index.php.j2
    dest="{{ APACHE_HTML_DIRECTORY }}/index.php"
    mode=0600
    owner=www-data
    group=www-data

- name: disable mpm_event module
  ansible.builtin.shell: a2dismod mpm_event

- name: enable mpm_prefork module
  ansible.builtin.shell: a2enmod mpm_prefork

- name: enable php7.4 module
  ansible.builtin.shell: a2enmod php7.4

- name: enable rewrite module
  ansible.builtin.shell: a2enmod rewrite

- name: restart Apache
  ansible.builtin.service:
    name=apache2
    state=restarted
