- name: check out luasandbox from git
  ansible.builtin.git:
    repo={{ MW_LUASANDBOX_GIT_URL }}
    dest=/usr/src/luasandbox
    version=master

- name: compile and install luasandbox
  ansible.builtin.shell: phpize && ./configure --prefix=/usr/lib/php && make all install
  args:
    chdir: /usr/src/luasandbox

- name: copy luasandbox initialization file
  ansible.builtin.copy:
    src=luasandbox.ini
    dest=/etc/php/7.3/apache2/conf.d/20-luasandbox.ini
    mode=0600
    owner=root
