- name: check out MediaWiki from git
  git:
    repo={{ MW_GIT_URL }}
    dest={{ MW_CODE_RELEASE_DIRECTORY }}
    version=remotes/origin/{{ MW_RELEASE }}

- name: get MediaWiki libraries using composer
  shell: composer update
    chdir={{ MW_CODE_RELEASE_DIRECTORY }}

- name: remove LocalSettings.php if it already exists
  file:
    path={{ MW_CODE_RELEASE_DIRECTORY }}/LocalSettings.php
    state=absent

- name: create subdirectory for wiki farm config files
  file:
    path={{ MW_WIKIFARM_CONFIG_DIRECTORY }}
    state=directory

- name: remove empty wiki schema from database if it already exists
  mysql_db:
    name={{ EMPTY_WIKI_NAME }}
    login_host=localhost
    login_user={{ DB_WIKI_USER }}
    login_password={{ DB_WIKI_PASSWORD }}
    state=absent

- name: create empty wiki and LocalSettings file
  shell: php maintenance/install.php {{ EMPTY_WIKI_NAME }} {{ WIKI_ADMIN_USER }} --pass "{{ WIKI_ADMIN_PASSWORD }}" --dbserver localhost --dbname {{ EMPTY_WIKI_NAME }} --dbuser {{ DB_WIKI_USER }} --dbpass "{{ DB_WIKI_PASSWORD }}"
    chdir={{ MW_CODE_RELEASE_DIRECTORY }}

- name: extract keys from generated LocalSettings.php file
  shell: echo "<?php" > {{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Keys.php; grep "^\$wgSecretKey" LocalSettings.php >> {{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Keys.php; grep "^\$wgUpgradeKey" LocalSettings.php >> {{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Keys.php
    chdir={{ MW_CODE_RELEASE_DIRECTORY }}

- name: remove newly created LocalSettings.php
  file:
    path={{ MW_CODE_RELEASE_DIRECTORY }}/LocalSettings.php
    state=absent

- name: copy configuration files 1/4
  template:
    src=LocalSettings.php.j2
    dest={{ MW_CODE_RELEASE_DIRECTORY }}/LocalSettings.php
    mode=644
    owner=www-data
    group=www-data

- name: copy configuration files 2/4
  copy:
    src={{ item }}
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/{{ item }}
    mode=644
    owner=www-data
    group=www-data
  with_items:
    - Debug.php
    - Upload.php
    - Permissions.php

- name: copy configuration files 3/4
  template:
    src=Server.php.j2
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Server.php
    mode=644
    owner=www-data
    group=www-data

- name: copy configuration files 4/4
  template:
    src=Email.php.j2
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Email.php
    mode=644
    owner=www-data
    group=www-data

- name: create link to the newly installed MediaWiki version
  file:
    src={{ MW_CODE_RELEASE_DIRECTORY }}
    dest={{ MW_CODE_DIRECTORY }}
    state=link
