- name: check out MediaWiki from git
  ansible.builtin.git:
    repo={{ MW_GIT_URL }}
    dest={{ MW_CODE_RELEASE_DIRECTORY }}
    version=remotes/origin/{{ MW_RELEASE }}

- name: get MediaWiki libraries using composer
  community.general.composer:
    command: install
    working_dir: "{{ MW_CODE_RELEASE_DIRECTORY }}"

- name: remove LocalSettings.php if it already exists
  ansible.builtin.file:
    path={{ MW_CODE_RELEASE_DIRECTORY }}/LocalSettings.php
    state=absent

- name: create subdirectory for wiki farm config files
  ansible.builtin.file:
    path={{ MW_WIKIFARM_CONFIG_DIRECTORY }}
    state=directory

- name: remove empty wiki schema from database if it already exists
  community.mysql.mysql_db:
    name={{ EMPTY_WIKI_NAME }}
    login_host=localhost
    login_unix_socket=/var/run/mysqld/mysqld.sock
    state=absent

- name: create empty wiki and LocalSettings file
  ansible.builtin.shell: php maintenance/install.php {{ EMPTY_WIKI_NAME }} {{ WIKI_ADMIN_USER }} --pass "{{ WIKI_ADMIN_PASSWORD }}" --dbserver localhost --dbname {{ EMPTY_WIKI_NAME }} --dbuser {{ DB_WIKI_USER }} --dbpass "{{ DB_WIKI_PASSWORD }}"
    chdir={{ MW_CODE_RELEASE_DIRECTORY }}

- name: extract keys from generated LocalSettings.php file
  ansible.builtin.shell: echo "<?php" > {{ MW_CONFIG_DIRECTORY }}/SERVER/Keys.php; grep "^\$wgSecretKey" LocalSettings.php >> {{ MW_CONFIG_DIRECTORY }}/SERVER/Keys.php; grep "^\$wgUpgradeKey" LocalSettings.php >> {{ MW_CONFIG_DIRECTORY }}/SERVER/Keys.php
    chdir={{ MW_CODE_RELEASE_DIRECTORY }}

- name: remove newly created LocalSettings.php
  ansible.builtin.file:
    path={{ MW_CODE_RELEASE_DIRECTORY }}/LocalSettings.php
    state=absent

- name: copy configuration files 1/3
  ansible.builtin.template:
    src=server.yaml.j2
    dest={{ MW_CONFIG_DIRECTORY }}/SERVER/server.yaml
    mode=644
    owner=www-data
    group=www-data

- name: copy configuration files 2/3
  ansible.builtin.copy:
    src={{ item }}
    dest={{ MW_CONFIG_DIRECTORY }}/SERVER/{{ item }}
    mode=644
    owner=www-data
    group=www-data
  with_items:
    - debug.yaml
    - uploads.yaml
    - permissions.yaml

- name: create link to the newly installed MediaWiki version
  ansible.builtin.file:
    src={{ MW_CODE_RELEASE_DIRECTORY }}
    dest={{ MW_CODE_DIRECTORY }}
    state=link
